baseURL = "https://diy.kabinet.com.pl/"
languageCode = "pl-pl"
title = "Smart Home DIY"
theme = "PaperMod"
defaultContentLanguage = "pl"
enableRobotsTXT = true
paginate = 10

[params]
  author = "Krzysztof"
  description = "Dokumentacja i projekty Smart Home  D I Y"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hideSummary = false
  ShowShareButtons = true
  homeInfoParams = { Title = "Smart Home DIY", Content = "Witaj na moim blogu poświęconym automatyzacji domu z Home Assistant." }

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Wpisy"
    url = "/posts/"
    weight = 1

[markup]
  [markup.highlight]
    noClasses = false
